name: Setup_CI

on:
  workflow_call:
    secrets:
      inherit

concurrency:
  group: ${{ github.event_name != 'pull_request' && github.run_id || github.ref }}
  cancel-in-progress: true

jobs:

  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: ./autogen.sh && ./configure --enable-dev-mode && make distcheck

      - name: Check installation with Autotools
        env:
          CI_SETUP: ${{ runner.temp }}/${{ github.run_id }}${{ github.action }}/install
        run: |
          ./autogen.sh && ./configure --prefix=${{ env.CI_SETUP }} && make clean && make install && ls -RlAh ${{ env.CI_SETUP }}
          gcc -o ecdsa examples/ecdsa.c $(PKG_CONFIG_PATH=${{ env.CI_SETUP }}/lib/pkgconfig pkg-config --cflags --libs secp256k1) -Wl,-rpath,"${{ env.CI_SETUP }}/lib" && ./ecdsa

      - name: Check installation with CMake
        env:
          CI_BUILD: ${{ runner.temp }}/${{ github.run_id }}${{ github.action }}/build
          CI_SETUP: ${{ runner.temp }}/${{ github.run_id }}${{ github.action }}/setup
        run: |
          cmake -B ${{ env.CI_BUILD }} -DCMAKE_SETUP_PREFIX=${{ env.CI_SETUP }} && cmake --build ${{ env.CI_BUILD }} && cmake --install ${{ env.CI_BUILD }} && ls -RlAh ${{ env.CI_SETUP }}
          gcc -o ecdsa examples/ecdsa.c -I ${{ env.CI_SETUP }}/include -L ${{ env.CI_SETUP }}/lib*/ -l secp256k1 -Wl,-rpath,"${{ env.CI_SETUP }}/lib",-rpath,"${{ env.CI_SETUP }}/lib64" && ./ecdsa
